include::{mod-loc}attributes.adoc[]

:context: skupper-operator
//Category: skupper-operator
// Type: assembly

= Using the Skupper Operator

[role="system:abstract"]
The {SkupperOperatorName} creates and manages {skupper-name} sites in {cluster-brand}. 

[id='adding-operator-{context}']
== Adding the Skupper Operator to your cluster

The options for installing the Operator are:

* xref:installing-operator-using-cli-{context}[]
* xref:installing-operator-using-olm-{context}[]
 
[NOTE]
====
Installing an Operator requires administrator-level privileges for your {cluster-brand} cluster.
====

[id='installing-operator-using-cli-{context}']
== Installing the Operator using the CLI

The procedures in this section show how to use the OpenShift command-line interface (CLI) to install and deploy the latest version of the {SkupperOperatorName} in a given OpenShift project. 


[id='proc_br-getting-operator-code_{context}']
=== Getting the Operator code

:examples-file: skupper-operator-2.0-ocp-install-examples.zip

This procedure shows how to access and prepare the code you need to install the latest version of the Operator for {skupper-name}.

.Procedure

. In your web browser, navigate to the *Software Downloads* page for link:https://access.redhat.com/jbossnetwork/restricted/listSoftware.html?downloadType=distributions&product=jboss.amq.interconnect[{skupper-name} releases].

. Ensure that the value of the *Version* drop-down list is set to `{RouterVersion}` and the *Releases* tab is selected.

. Next to *AMQ Interconnect 2.0 Operator Installation and Example Files*, click *Download*.
+
Download of the `{examples-file}` compressed archive automatically begins.

. When the download has completed, move the archive to your chosen installation directory. The following example moves the archive to a directory called `~/router/operator`.
+
[source,bash,options="nowrap",subs="+attributes"]
----
$ mkdir ~/router
$ mv {examples-file} ~/router
----

. In your chosen installation directory, extract the contents of the archive. For example:
+
[source,bash,options="nowrap", subs="+attributes"]
----
$ cd ~/router
$ unzip {examples-file}
----

. Switch to the directory that was created when you extracted the archive. For example:
+
[source,bash,options="nowrap", subs="+attributes"]
----
$ cd operator
----

. Log in to {cluster-brand} as a cluster administrator. For example:
+
[source,bash,options="nowrap"]
----
$ oc login -u system:admin
----

. Specify the project in which you want to install the Operator. You can create a new project or switch to an existing one.

.. Create a new project:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc new-project __<project-name>__
----

.. Or, switch to an existing project:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc project __<project-name>__
----

. Create a service account to use with the Operator.
+
[source,bash,options="nowrap"]
----
$ oc create -f deploy/service_account.yaml
----

. Create a role for the Operator.
+
[source,bash,options="nowrap"]
----
$ oc create -f deploy/role.yaml
----

. Create a role binding for the Operator. The role binding binds the previously-created service account to the Operator role, based on the names you specified.
+
[source,bash,options="nowrap"]
----
$ oc create -f deploy/role_binding.yaml
----

In the procedure that follows, you deploy the Operator in your project.



[id='proc-br-deploying-operator_{context}']
=== Deploying the Skupper Operator using the CLI

The procedure in this section shows how to use the OpenShift command-line interface (CLI) to deploy the latest version of the Operator for {skupper-name} {RouterVersion} in your OpenShift project.

.Prerequisites

* You must have already prepared your OpenShift project for the Operator deployment. See xref:proc_br-getting-operator-code_{context}[].

* Before you can follow the procedure in this section, you must first complete the steps described in
link:https://access.redhat.com/RegistryAuthentication[Red Hat Container Registry Authentication^].


.Procedure

. In the OpenShift command-line interface (CLI), log in to {cluster-brand} as a cluster administrator. For example:
+
[source,bash,options="nowrap"]
----
$ oc login -u system:admin
----

. Switch to the project that you previously prepared for the Operator deployment. For example:
+
[source,bash,options="nowrap",subs="+quotes"]
----
$ oc project __<project-name>__
----

. Switch to the directory that was created when you previously extracted the Operator installation archive. For example:
+
[source,bash,options="nowrap", subs="+attributes"]
----
$ cd ~/router/operator/skupper-operator-{RouterVersion}-ocp-install-examples
----

. Create a CatalogSource in the `openshift-marketplace` namespace:
+
[source,bash,options="nowrap"]
----
$ oc apply -f ocp/00-cs.yaml
----

. Make sure the skupper-operator catalog pod is running before continuing:
+
[source,bash,options="nowrap"]
----
$ oc -n openshift-marketplace get pods | grep skupper-operator
----

. Create an OperatorGroup in the `my-namespace` project:
+
[source,bash,options="nowrap"]
----
$ oc apply -f ocp/10-og.yaml
----

. Create a Subscription  in the `my-namespace` project:
+
[source,bash,options="nowrap"]
----
$ oc apply -f ocp/20-sub.yaml
----

. Verify that the Operator is running:
+
[source,bash,options="nowrap"]
----
$ oc get pods -n my-namespace

NAME                                     READY   STATUS    RESTARTS   AGE
skupper-site-controller-d7b57964-gxms6   1/1     Running   0          1m
----
+
If the output does not report the pod is running, use the following command to determine the issue that prevented it from running:
+
----
$ oc describe pod -l name=skupper-operator
----

.Additional resources
* For an alternative method of installing the {skupper-name} Operator that uses the OperatorHub graphical interface, see xref:installing-operator-using-olm-{context}[].


[id='installing-operator-using-olm-{context}']
== Installing the Skupper Operator using the Operator Lifecycle Manager

The procedures in this section show how to use the OperatorHub to install and deploy the latest version of the {SkupperOperatorName} in a given OpenShift project. 

In {cluster-brand} 4.1 and later, the __Operator Lifecycle Manager__ (OLM) helps users install, update, and generally manage the lifecycle of all Operators and their associated services running across their clusters. It is part of the Operator Framework, an open source toolkit designed to manage Kubernetes native applications (Operators) in an effective, automated, and scalable way.

.Prerequisites

* Access to an {cluster-brand} {OpenShiftVersion} cluster using a `cluster-admin` account.

.Procedure

. In the {cluster-brand} web console, navigate to menu:Operators[OperatorHub].

. Choose `{SkupperOperatorName}` from the list of available Operators, and then click btn:[Install].

. On the *Operator Installation* page, select the namespace into which you want to install the Operator, and then click btn:[Install].
+
The *Installed Operators* page appears displaying the status of the Operator installation.

. Verify that the {skupper-name} Operator is displayed and wait until the *Status* changes to *Succeeded*.

. If the installation is not successful, troubleshoot the error:

.. Click `{SkupperOperatorName}` on the *Installed Operators* page.

.. Select the *Subscription* tab and view any failures or errors.